/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/naming-convention */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Pixel (https://sketchfab.com/stefan.lengyel1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/medieval-fantasy-book-06d5a80a04fc4c5ab552759e9a97d91a
Title: Medieval Fantasy Book
*/

import { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { a } from "@react-spring/three";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import bookScene from "../assets/3d/book.glb";

type GLTFResult = GLTF & {
  nodes: Record<string, THREE.Mesh>;
  materials: Record<string, THREE.Material>;
};

type BookProps = JSX.IntrinsicElements["group"];

const Book = (props: BookProps) => {
  const group = useRef<any>();
  const { nodes, materials, animations } = useGLTF(bookScene) as GLTFResult;
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    Object.values(materials).forEach((material) => {
      if (material instanceof THREE.MeshStandardMaterial) {
        material.roughness = 0.5;
        material.metalness = 0.5;
        material.needsUpdate = true;
      }
    });

    if (actions["The Life"]) {
      actions["The Life"].play();
    }
  }, [actions, materials]);

  return (
    <a.group ref={group} {...props}>
      <a.group name="Sketchfab_Scene">
        <a.group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <a.group
            name="dad255dd2cf24ae0bb357684e49722b4fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <a.group name="Object_2">
              <a.group name="RootNode">
                <a.group
                  name="Scene"
                  position={[-4.79372597, 0, 0.27796173]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <a.group
                    name="Object_5"
                    position={[-14.00022888, 15.78759384, 4.33730507]}
                  >
                    <mesh
                      name="Scene_Texture-base_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Scene_Texture-base_0"]?.geometry}
                      material={materials["Texture-base"] ?? new THREE.MeshStandardMaterial()}
                    />
                    <mesh
                      name="Scene_Texture-base_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes["Scene_Texture-base_0_1"]?.geometry}
                      material={materials["Texture-base"] ?? new THREE.MeshStandardMaterial()}
                    />
                    <mesh
                      name="Scene_Texture-base-gloss-jpg_0"
                      castShadow
                      receiveShadow
                      geometry={
                        nodes["Scene_Texture-base-gloss-jpg_0"]?.geometry
                      }
                      material={materials["Texture-base-gloss-jpg"] ?? new THREE.MeshStandardMaterial()}
                    />
                    <mesh
                      name="Scene_Book-tittle_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Scene_Book-tittle_0"]?.geometry}
                      material={materials["Book-tittle"] ?? new THREE.MeshStandardMaterial()}
                    />
                  </a.group>
                  <a.group
                    name="Mill-wind-wheel"
                    position={[-35.78340912, -27.19170189, 3.88831043]}
                    rotation={[0.44533695, -0.44740808, -0.49810387]}
                    scale={[0.99999982, 1.00000024, 0.99999994]}
                  >
                    <group
                      name="Object_11"
                      position={[-8.25311565, 39.88404083, -25.75028419]}
                      rotation={[-0.60692794, 0.13762521, 0.64419751]}
                    >
                      <mesh
                        name="Mill-wind-wheel_Texture-base_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes["Mill-wind-wheel_Texture-base_0"]?.geometry
                        }
                        material={materials["Texture-base"] ?? new THREE.MeshStandardMaterial()}
                      />
                    </group>
                  </a.group>
                  <a.group
                    name="Mill-water-wheel"
                    position={[3.70824051, -15.39521599, -0.44395638]}
                    rotation={[-1.9198622, 0, 0]}
                  >
                    <a.group
                      name="Object_14"
                      position={[-17.70846939, 31.18280983, 4.78126144]}
                    >
                      <mesh
                        name="Mill-water-wheel_Texture-base_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes["Mill-water-wheel_Texture-base_0"]?.geometry
                        }
                        material={materials["Texture-base"] ?? new THREE.MeshStandardMaterial()}
                      />
                    </a.group>
                  </a.group>
                </a.group>
                <a.group
                  name="flag"
                  position={[-11.51328087, 12.49712181, -6.75236702]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 6]}
                >
                  <a.group
                    name="Object_17"
                    position={[-7.26199007, 9.03522682, -8.15981674]}
                  >
                    <mesh
                      name="0"
                      castShadow
                      receiveShadow
                      geometry={nodes["0"]?.geometry ?? new THREE.BufferGeometry()}
                      material={materials["Texture-base"] ?? new THREE.MeshStandardMaterial({ color: 0xcccccc })}
                      morphTargetDictionary={nodes["0"]?.morphTargetDictionary ?? {}}
                      morphTargetInfluences={nodes["0"]?.morphTargetInfluences ?? []}
                    />
                  </a.group>
                </a.group>
                <a.group
                  name="flag-second"
                  position={[-11.49352741, 12.55176544, -26.24493599]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <a.group
                    name="Object_20"
                    position={[-7.26199007, 9.03522682, -8.15981674]}
                  >
                    <mesh
                      name="1"
                      castShadow
                      receiveShadow
                      geometry={nodes["1"]?.geometry ?? new THREE.BufferGeometry()}
                      material={materials["Texture-base"] ?? new THREE.MeshStandardMaterial({ color: 0xcccccc })}
                      morphTargetDictionary={nodes["1"]?.morphTargetDictionary ?? {}}
                      morphTargetInfluences={nodes["1"]?.morphTargetInfluences ?? []}
                    />
                  </a.group>
                </a.group>
                <a.group
                  name="Waterfall"
                  position={[-4.794, 0, 0.351]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <a.group name="Object_23" position={[-14, 15.788, 4.337]}>
                    <mesh
                      name="Waterfall_Texture-base-gloss-jpg_0"
                      castShadow
                      receiveShadow
                        geometry={
                          nodes["Waterfall_Texture-base-gloss-jpg_0"]?.geometry
                        }
                        material={materials["Texture-base-gloss-jpg"] ?? new THREE.MeshStandardMaterial()}
                    />
                  </a.group>
                </a.group>
                <a.group
                  name="deers"
                  position={[-23.122, -0.049, 14.878]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <a.group name="Object_26" position={[4.328, 30.387, 4.387]}>
                    <mesh
                      name="deers_Texture-base_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["deers_Texture-base_0"]?.geometry}
                      material={materials["Texture-base"] ?? new THREE.MeshStandardMaterial()}
                    />
                  </a.group>
                </a.group>
              </a.group>
            </a.group>
          </a.group>
        </a.group>
      </a.group>
    </a.group>
  );
};

export default Book;

useGLTF.preload(bookScene);
