/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/naming-convention */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: PotionMonkey (https://sketchfab.com/PotionMonkey)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ciri-chibi-d1ab30ad4e4e42a9a96a5758e6eac9e7
Title: Ciri Chibi
*/

import React, { useEffect, useRef } from 'react'
import { useAnimations, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib';

import ciriScene from '../assets/3d/ciri.glb'
import ciriMat from '../assets/3d/ciri1.glb'
import bookScene from '../assets/3d/book.glb';
import * as THREE from 'three';
import { useFrame } from '@react-three/fiber';

type GLTFResult = GLTF & {
    nodes: Record<string, THREE.Mesh>;
    materials: Record<string, THREE.Material>;
};

const Ciri = (props) => {

  const group = useRef<any>();
  const { nodes, animations  } = useGLTF(ciriScene) as GLTFResult;
  const { materials } = useGLTF(ciriMat);

  const { actions } = useAnimations(animations, group);

    useEffect(() => {
        
        if (actions['Armature|mixamo.com|Layer0']) {
          actions['Armature|mixamo.com|Layer0'].play();
        }
      }, [actions]);

      const clock = useRef(0);
      const baseY = -1.6; // Base Y position from adjustCiriForScreenSize
      const surfaceOffset = 0.1; // Offset to keep Ciri above the surface

  return (
    <group ref={group} {...props} >
    <group name="Scene">
      <group name="6cde9eeb2b3a4e03a99be448a154a10cfbx" rotation={[-Math.PI, 0, 0]} scale={0.01}>
        <group name="RootNode1">
          <group name="Ciri_GEO">
            <group name="bag" />
            <group name="belt" />
            <group
              name="dagger"
              position={[-12.097, 4.58, -48.253]}
              rotation={[-0.074, 1.139, -2.518]}>
              <group name="handle1" />
              <group name="sheath" />
            </group>
            <group name="ears" />
            <group name="hair">
              <group name="bun" />
              <group name="Hair_alpha01" />
              <group name="Hair_alpha02" />
              <group name="Hair_alpha03" />
              <group name="Hair_alpha04" />
              <group name="Hair_alpha05" />
              <group name="Hair_alpha06" />
              <group name="Hair_lrg01" />
              <group name="Hair_lrg02" />
              <group name="Hair_lrg03" />
              <group name="Hair_lrg05" />
              <group name="Hair_lrg06" />
              <group name="Hair_lrg07" />
              <group name="Hair_lrg08" />
              <group name="Hair_sml02" />
              <group name="Hair_sml03" />
            </group>
            <group name="hands" />
            <group name="Head" />
            <group name="legs" />
            <group name="shirtLink" />
            <group
              name="sword"
              position={[-13.516, -10.508, -82.603]}
              rotation={[Math.PI / 2, 0, 0.869]}>
              <group name="guard" />
              <group name="handle" />
              <group name="pummel" />
              <group name="sword1" />
            </group>
            <group name="torso" />
          </group>
        </group>
      </group>
      <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <skinnedMesh
        castShadow
        receiveShadow
          name="bag_Ciri_mat_0"
          geometry={nodes.bag_Ciri_mat_0.geometry}
          material={materials.Ciri_mat}
          skeleton={nodes.bag_Ciri_mat_0.skeleton}
        />
        <skinnedMesh
        castShadow
        receiveShadow
          name="belt_Ciri_mat_0"
          geometry={nodes.belt_Ciri_mat_0.geometry}
          material={materials.Ciri_mat}
          skeleton={nodes.belt_Ciri_mat_0.skeleton}
        />
        <skinnedMesh
        castShadow
        receiveShadow
          name="bun_Ciri_mat_0"
          geometry={nodes.bun_Ciri_mat_0.geometry}
          material={materials.Ciri_mat}
          skeleton={nodes.bun_Ciri_mat_0.skeleton}
        />
        <skinnedMesh
        castShadow
        receiveShadow
          name="ears_Ciri_mat_0"
          geometry={nodes.ears_Ciri_mat_0.geometry}
          material={materials.Ciri_mat}
          skeleton={nodes.ears_Ciri_mat_0.skeleton}
        />
        <skinnedMesh
        castShadow
        receiveShadow
          name="guard_Ciri_mat_0"
          geometry={nodes.guard_Ciri_mat_0.geometry}
          material={materials.Ciri_mat}
          skeleton={nodes.guard_Ciri_mat_0.skeleton}
        />
        <skinnedMesh
        castShadow
        receiveShadow
          name="Hair_alpha01_Ciri_mat_0"
          geometry={nodes.Hair_alpha01_Ciri_mat_0.geometry}
          material={materials.Ciri_mat}
          skeleton={nodes.Hair_alpha01_Ciri_mat_0.skeleton}
        />
        <skinnedMesh
        castShadow
        receiveShadow
          name="Hair_alpha02_Ciri_mat_0"
          geometry={nodes.Hair_alpha02_Ciri_mat_0.geometry}
          material={materials.Ciri_mat}
          skeleton={nodes.Hair_alpha02_Ciri_mat_0.skeleton}
        />
        <skinnedMesh
        castShadow
        receiveShadow
          name="Hair_alpha03_Ciri_mat_0"
          geometry={nodes.Hair_alpha03_Ciri_mat_0.geometry}
          material={materials.Ciri_mat}
          skeleton={nodes.Hair_alpha03_Ciri_mat_0.skeleton}
        />
        <skinnedMesh
        castShadow
        receiveShadow
          name="Hair_alpha04_Ciri_mat_0"
          geometry={nodes.Hair_alpha04_Ciri_mat_0.geometry}
          material={materials.Ciri_mat}
          skeleton={nodes.Hair_alpha04_Ciri_mat_0.skeleton}
        />
        <skinnedMesh
        castShadow
        receiveShadow
          name="Hair_alpha05_Ciri_mat_0"
          geometry={nodes.Hair_alpha05_Ciri_mat_0.geometry}
          material={materials.Ciri_mat}
          skeleton={nodes.Hair_alpha05_Ciri_mat_0.skeleton}
        />
        <skinnedMesh
        castShadow
        receiveShadow
          name="Hair_alpha06_Ciri_mat_0"
          geometry={nodes.Hair_alpha06_Ciri_mat_0.geometry}
          material={materials.Ciri_mat}
          skeleton={nodes.Hair_alpha06_Ciri_mat_0.skeleton}
        />
        <skinnedMesh
        castShadow
        receiveShadow
          name="Hair_lrg01_Ciri_mat_0"
          geometry={nodes.Hair_lrg01_Ciri_mat_0.geometry}
          material={materials.Ciri_mat}
          skeleton={nodes.Hair_lrg01_Ciri_mat_0.skeleton}
        />
        <skinnedMesh
        castShadow
        receiveShadow
          name="Hair_lrg02_Ciri_mat_0"
          geometry={nodes.Hair_lrg02_Ciri_mat_0.geometry}
          material={materials.Ciri_mat}
          skeleton={nodes.Hair_lrg02_Ciri_mat_0.skeleton}
        />
        <skinnedMesh
        castShadow
        receiveShadow
          name="Hair_lrg03_Ciri_mat_0"
          geometry={nodes.Hair_lrg03_Ciri_mat_0.geometry}
          material={materials.Ciri_mat}
          skeleton={nodes.Hair_lrg03_Ciri_mat_0.skeleton}
        />
        <skinnedMesh
        castShadow
        receiveShadow
          name="Hair_lrg05_Ciri_mat_0"
          geometry={nodes.Hair_lrg05_Ciri_mat_0.geometry}
          material={materials.Ciri_mat}
          skeleton={nodes.Hair_lrg05_Ciri_mat_0.skeleton}
        />
        <skinnedMesh
        castShadow
        receiveShadow
          name="Hair_lrg06_Ciri_mat_0"
          geometry={nodes.Hair_lrg06_Ciri_mat_0.geometry}
          material={materials.Ciri_mat}
          skeleton={nodes.Hair_lrg06_Ciri_mat_0.skeleton}
        />
        <skinnedMesh
        castShadow
          receiveShadow
          name="Hair_lrg07_Ciri_mat_0"
          geometry={nodes.Hair_lrg07_Ciri_mat_0.geometry}
          material={materials.Ciri_mat}
          skeleton={nodes.Hair_lrg07_Ciri_mat_0.skeleton}
        />
        <skinnedMesh
        castShadow
          receiveShadow
          name="Hair_lrg08_Ciri_mat_0"
          geometry={nodes.Hair_lrg08_Ciri_mat_0.geometry}
          material={materials.Ciri_mat}
          skeleton={nodes.Hair_lrg08_Ciri_mat_0.skeleton}
        />
        <skinnedMesh
        castShadow
          receiveShadow
          name="Hair_sml02_Ciri_mat_0"
          geometry={nodes.Hair_sml02_Ciri_mat_0.geometry}
          material={materials.Ciri_mat}
          skeleton={nodes.Hair_sml02_Ciri_mat_0.skeleton}
        />
        <skinnedMesh
        castShadow
          receiveShadow
          name="Hair_sml03_Ciri_mat_0"
          geometry={nodes.Hair_sml03_Ciri_mat_0.geometry}
          material={materials.Ciri_mat}
          skeleton={nodes.Hair_sml03_Ciri_mat_0.skeleton}
        />
        <skinnedMesh
        castShadow
          receiveShadow
          name="handle_Ciri_mat_0"
          geometry={nodes.handle_Ciri_mat_0.geometry}
          material={materials.Ciri_mat}
          skeleton={nodes.handle_Ciri_mat_0.skeleton}
        />
        <skinnedMesh
        castShadow
          receiveShadow
          name="handle_Ciri_mat_01"
          geometry={nodes.handle_Ciri_mat_01.geometry}
          material={materials.Ciri_mat}
          skeleton={nodes.handle_Ciri_mat_01.skeleton}
        />
        <skinnedMesh
        castShadow
          receiveShadow
          name="hands_Ciri_mat_0"
          geometry={nodes.hands_Ciri_mat_0.geometry}
          material={materials.Ciri_mat}
          skeleton={nodes.hands_Ciri_mat_0.skeleton}
        />
        <skinnedMesh
        castShadow
          receiveShadow
          name="Head_Ciri_mat_0"
          geometry={nodes.Head_Ciri_mat_0.geometry}
          material={materials.Ciri_mat}
          skeleton={nodes.Head_Ciri_mat_0.skeleton}
        />
        <skinnedMesh
        castShadow
          receiveShadow
          name="legs_Ciri_mat_0"
          geometry={nodes.legs_Ciri_mat_0.geometry}
          material={materials.Ciri_mat}
          skeleton={nodes.legs_Ciri_mat_0.skeleton}
        />
        <skinnedMesh
        castShadow
          receiveShadow
          name="pummel_Ciri_mat_0"
          geometry={nodes.pummel_Ciri_mat_0.geometry}
          material={materials.Ciri_mat}
          skeleton={nodes.pummel_Ciri_mat_0.skeleton}
        />
        <skinnedMesh
        castShadow
          receiveShadow
          name="sheath_Ciri_mat_0"
          geometry={nodes.sheath_Ciri_mat_0.geometry}
          material={materials.Ciri_mat}
          skeleton={nodes.sheath_Ciri_mat_0.skeleton}
        />
        <skinnedMesh
        castShadow
          receiveShadow
          name="shirtLink_Ciri_mat_0"
          geometry={nodes.shirtLink_Ciri_mat_0.geometry}
          material={materials.Ciri_mat}
          skeleton={nodes.shirtLink_Ciri_mat_0.skeleton}
        />
        <skinnedMesh
        castShadow
          receiveShadow
          name="sword_Ciri_mat_0"
          geometry={nodes.sword_Ciri_mat_0.geometry}
          material={materials.Ciri_mat}
          skeleton={nodes.sword_Ciri_mat_0.skeleton}
        />
        <skinnedMesh
        castShadow
          receiveShadow
          name="torso_Ciri_mat_0"
          geometry={nodes.torso_Ciri_mat_0.geometry}
          material={materials.Ciri_mat}
          skeleton={nodes.torso_Ciri_mat_0.skeleton}
        />
        <primitive object={nodes.mixamorigHips} />
      </group>
    </group>
  </group>
  )
}

export default Ciri;

useGLTF.preload(ciriScene)
