/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: DuNguyn - Assets store (https://sketchfab.com/nguyenvuduc2000)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/evironment-pack-egypt-map-3049b31b9aba4f6d94345573be670aca
Title: Evironment Pack - Egypt Map
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import { a } from '@react-spring/three'

import egyptScene from '../assets/3d/egypt.glb'

const Island = (props) => {
    const egyptRef = useRef(); 
  const { nodes, materials } = useGLTF(egyptScene) as any;
  return (
    <a.group ref={egyptRef} {...props} >
      <a.group rotation={[-Math.PI / 2, 0, 0]} scale={6.198}>
        <a.group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes.Ao_ONen_v03_SG_0.geometry}
            material={materials.ONen_v03_SG}
          />
          <mesh
            geometry={nodes.Nha_Tien_NhaChinh_Tien_SG_0.geometry}
            material={materials.NhaChinh_Tien_SG}
          />
          <mesh
            geometry={nodes.Nha_Meo_NhaChinh_Meo_SG_0.geometry}
            material={materials.NhaChinh_Meo_SG}
          />
          <mesh
            geometry={nodes.Nha_Sach_NhaChinh_Sach_SG_0.geometry}
            material={materials.NhaChinh_Sach_SG}
          />
          <mesh
            geometry={nodes.Light_Light_SG_0.geometry}
            material={materials.Light_SG}
          />
          <mesh
            geometry={nodes.Water_Water_SG_0.geometry}
            material={materials.Water_SG}
          />
          <mesh
            geometry={nodes.O_Nen_L1_ONen_v02_SG_0.geometry}
            material={materials.ONen_v02_SG}
          />
          <mesh
            geometry={nodes.nen1_ONen_v01_SG_0.geometry}
            material={materials.ONen_v01_SG}
          />
          <mesh
            geometry={nodes.O1_ONen_v01_SG_0.geometry}
            material={materials.ONen_v01_SG}
          />
          <mesh
            geometry={nodes.CauThanh1_ONen_v01_SG_0.geometry}
            material={materials.ONen_v01_SG}
          />
          <mesh
            geometry={nodes.LaSen1_ONen_v03_SG_0.geometry}
            material={materials.ONen_v03_SG}
          />
          <mesh
            geometry={nodes.NhaPhu1_NhaPhu_SG_0.geometry}
            material={materials.NhaPhu_SG}
          />
          <mesh
            geometry={nodes.Tru1_Tru_SG_0.geometry}
            material={materials.Tru_SG}
          />
          <mesh
            geometry={nodes.GachDai1_ONen_v02_SG_0.geometry}
            material={materials.ONen_v02_SG}
          />
          <mesh
            geometry={nodes.GachDai1_ONen_v01_SG_0.geometry}
            material={materials.ONen_v01_SG}
          />
          <mesh
            geometry={nodes.Da1_Da_SG_0.geometry}
            material={materials.Da_SG}
          />
          <mesh
            geometry={nodes.Da1_NhaChinh_Tien_SG_0.geometry}
            material={materials.NhaChinh_Tien_SG}
          />
        </a.group>
      </a.group>
    </a.group>
  )
}

export default Island;